Shape text
shaminoo/SmallBasic-Online pull request #12
Opened 2018-07-24 22:46 UTC by MatthewMeacham

Created the Text shape based on what Hongchao Guan had done

2018-07-24 22:51 UTC, shaminoo approved these changes

2018-07-24 23:37 UTC, allisoninman approved these changes
As is, I approve this. [This PR](https://github.com/shaminoo/SmallBasic-Online/pull/7) will require that the following code be added to this class:

    public move(x: number, y: number): void {
        this.instance.x(x);
        this.instance.y(y);
    }

2018-07-24 23:41 UTC, allisoninman requested changes
See other comment, accidentally hit approve

2018-07-25 03:31 UTC, MicahElizabeth commented
SetText(shapeName, text) is also a functionality we need to support for the shape base class. I'm not 100% sure what the spec is on the function.

2018-07-25 04:04 UTC, MicahElizabeth commented on src/app/shapes/Text.ts
> +
I think Text is already a class, we might have to call this TextShape or something

2018-07-25 04:05 UTC, MicahElizabeth requested changes

2018-07-25 04:05 UTC, MicahElizabeth commented on src/app/shapes/Text.ts
> +
I think Text is already a class, we might have to call this TextShape or something

2018-07-25 04:20 UTC, MicahElizabeth commented
I will work on these changes. 😃

2018-07-25 04:41 UTC, MicahElizabeth approved these changes

2018-07-25 06:35 UTC, allisoninman approved these changes
LGTM!

2018-07-25 06:39 UTC, merged